services:
  backend:
    build: ./mern/backend
    container_name: backend
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - MONGODB_URI=${MONGODB_URI}

  frontend:
    build: ./mern/frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

