services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./db_data:/data/db

  backend:
    build: ./mern/backend
    container_name: backend
    ports:
      - "5050:5050"
    depends_on:
      - mongodb
    environment:
      - PORT=5050
      - MONGODB_URI=mongodb://mongodb:27017
      - FRONTEND_URL=http://localhost:5173

  frontend:
    build: ./mern/frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend


