apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mern-chart.fullname" . }}-frontend
  labels:
    app: frontend
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.image.registry }}/{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
        ports:
        - containerPort: {{ .Values.service.frontend.targetPort }}
        resources:
          {{- toYaml .Values.resources.frontend | nindent 12 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mern-chart.fullname" . }}-backend
  labels:
    app: backend
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.image.registry }}/{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
        ports:
        - containerPort: {{ .Values.service.backend.targetPort }}
        env:
        - name: MONGODB_URI
          value: "mongodb://{{ include "mern-chart.fullname" . }}-mongodb:27017"
        - name: PORT
          value: "{{ .Values.service.backend.port }}"
        resources:
          {{- toYaml .Values.resources.backend | nindent 12 }}